

from enum import Enum


class PermissionEnum(Enum):





# ENUM FOR 'AUTHENTIACTION' APP	

	# USER PERMISSIONS
	USER_CREATE = 'USER_CREATE'
	USER_UPDATE = 'USER_UPDATE'
	USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
	USER_DELETE = 'USER_DELETE'
	USER_LIST = 'USER_LIST'
	USER_DETAILS = 'USER_DETAILS'

	# PERMISSION PERMISSIONS
	PERMISSION_CREATE = 'PERMISSION_CREATE'
	PERMISSION_UPDATE = 'PERMISSION_UPDATE'
	PERMISSION_PARTIAL_UPDATE = 'PERMISSION_PARTIAL_UPDATE'
	PERMISSION_DELETE = 'PERMISSION_DELETE'
	PERMISSION_LIST = 'PERMISSION_LIST'
	PERMISSION_DETAILS = 'PERMISSION_DETAILS'

	# ROLE PERMISSION
	ROLE_CREATE = 'ROLE_CREATE'
	ROLE_UPDATE = 'ROLE_UPDATE'
	ROLE_DELETE = 'ROLE_DELETE'
	ROLE_LIST = 'ROLE_LIST'
	ROLE_DETAILS = 'ROLE_DETAILS'

	# COUNTRY PERMISSION
	COUNTRY_CREATE = 'COUNTRY_CREATE'
	COUNTRY_UPDATE = 'COUNTRY_UPDATE'
	COUNTRY_DELETE = 'COUNTRY_DELETE'
	COUNTRY_LIST = 'COUNTRY_LIST'
	COUNTRY_DETAILS = 'COUNTRY_DETAILS'

	# CITY PERMISSION
	CITY_CREATE = 'CITY_CREATE'
	CITY_UPDATE = 'CITY_UPDATE'
	CITY_DELETE = 'CITY_DELETE'
	CITY_LIST = 'CITY_LIST'
	CITY_DETAILS = 'CITY_DETAILS'

	# THANA PERMISSION
	THANA_CREATE = 'THANA_CREATE'
	THANA_UPDATE = 'THANA_UPDATE'
	THANA_DELETE = 'THANA_DELETE'
	THANA_LIST = 'THANA_LIST'
	THANA_DETAILS = 'THANA_DETAILS'

	# AREA PERMISSION
	AREA_CREATE = 'AREA_CREATE'
	AREA_UPDATE = 'AREA_UPDATE'
	AREA_DELETE = 'AREA_DELETE'
	AREA_LIST = 'AREA_LIST'
	AREA_DETAILS = 'AREA_DETAILS'

	# BRANCH PERMISSION
	BRANCH_CREATE = 'BRANCH_CREATE'
	BRANCH_UPDATE = 'BRANCH_UPDATE'
	BRANCH_DELETE = 'BRANCH_DELETE'
	BRANCH_LIST = 'BRANCH_LIST'
	BRANCH_DETAILS = 'BRANCH_DETAILS'

	# DEPARTMENT PERMISSION
	DEPARTMENT_CREATE = 'DEPARTMENT_CREATE'
	DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE'
	DEPARTMENT_DELETE = 'DEPARTMENT_DELETE'
	DEPARTMENT_LIST = 'DEPARTMENT_LIST'
	DEPARTMENT_DETAILS = 'DEPARTMENT_DETAILS'

	# EMPLOYEE PERMISSION
	EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
	EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
	EMPLOYEE_DELETE = 'EMPLOYEE_DELETE'
	EMPLOYEE_LIST = 'EMPLOYEE_LIST'
	EMPLOYEE_DETAILS = 'EMPLOYEE_DETAILS'

	# QUALIFICATION PERMISSION
	QUALIFICATION_CREATE = 'QUALIFICATION_CREATE'
	QUALIFICATION_UPDATE = 'QUALIFICATION_UPDATE'
	QUALIFICATION_DELETE = 'QUALIFICATION_DELETE'
	QUALIFICATION_LIST = 'QUALIFICATION_LIST'
	QUALIFICATION_DETAILS = 'QUALIFICATION_DETAILS'





# ENUM FOR 'PRODUCT' APP
# 	
	# PRODUCT PERMISSION
	PRODUCT_CREATE = 'PRODUCT_CREATE'
	PRODUCT_UPDATE = 'PRODUCT_UPDATE'
	PRODUCT_DELETE = 'PRODUCT_DELETE'
	PRODUCT_LIST = 'PRODUCT_LIST'
	PRODUCT_DETAILS = 'PRODUCT_DETAILS'

	# PRODUCT_TAG PERMISSION
	PRODUCT_TAG_CREATE = 'PRODUCT_TAG_CREATE'
	PRODUCT_TAG_UPDATE = 'PRODUCT_TAG_UPDATE'
	PRODUCT_TAG_DELETE = 'PRODUCT_TAG_DELETE'
	PRODUCT_TAG_LIST = 'PRODUCT_TAG_LIST'
	PRODUCT_TAG_DETAILS = 'PRODUCT_TAG_DETAILS'

	# ATTRIBUTE_SET PERMISSION
	ATTRIBUTE_SET_CREATE = 'ATTRIBUTE_SET_CREATE'
	ATTRIBUTE_SET_UPDATE = 'ATTRIBUTE_SET_UPDATE'
	ATTRIBUTE_SET_DELETE = 'ATTRIBUTE_SET_DELETE'
	ATTRIBUTE_SET_LIST = 'ATTRIBUTE_SET_LIST'
	ATTRIBUTE_SET_DETAILS = 'QUALIFICATION_DETAILS'

	# ATTRIBUTE_VALUE PERMISSION
	ATTRIBUTE_VALUE_CREATE = 'ATTRIBUTE_VALUE_CREATE'
	ATTRIBUTE_VALUE_UPDATE = 'ATTRIBUTE_VALUE_UPDATE'
	ATTRIBUTE_VALUE_DELETE = 'ATTRIBUTE_VALUE_DELETE'
	ATTRIBUTE_VALUE_LIST = 'ATTRIBUTE_VALUE_LIST'
	ATTRIBUTE_VALUE_DETAILS = 'ATTRIBUTE_VALUE_DETAILS'

	# ATTRIBUTE PERMISSION
	ATTRIBUTE_CREATE = 'ATTRIBUTE_CREATE'
	ATTRIBUTE_UPDATE = 'ATTRIBUTE_UPDATE'
	ATTRIBUTE_DELETE = 'ATTRIBUTE_DELETE'
	ATTRIBUTE_LIST = 'ATTRIBUTE_LIST'
	ATTRIBUTE_DETAILS = 'ATTRIBUTE_DETAILS'

	# BRAND PERMISSION
	BRAND_CREATE = 'BRAND_CREATE'
	BRAND_UPDATE = 'BRAND_UPDATE'
	BRAND_DELETE = 'BRAND_DELETE'
	BRAND_LIST = 'BRAND_LIST'
	BRAND_DETAILS = 'BRAND_DETAILS'

	# CATEGORY PERMISSION
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'

	# MANUFACTURER PERMISSION
	MANUFACTURER_CREATE = 'MANUFACTURER_CREATE'
	MANUFACTURER_UPDATE = 'MANUFACTURER_UPDATE'
	MANUFACTURER_DELETE = 'MANUFACTURER_DELETE'
	MANUFACTURER_LIST = 'MANUFACTURER_LIST'
	MANUFACTURER_DETAILS = 'MANUFACTURER_DETAILS'


	# COLOR PERMISSION
	COLOR_CREATE = 'COLOR_CREATE'
	COLOR_UPDATE = 'COLOR_UPDATE'
	COLOR_DELETE = 'COLOR_DELETE'
	COLOR_LIST = 'COLOR_LIST'
	COLOR_DETAILS = 'COLOR_DETAILS'


	# SIZE PERMISSION
	SIZE_CREATE = 'SIZE_CREATE'
	SIZE_UPDATE = 'SIZE_UPDATE'
	SIZE_DELETE = 'SIZE_DELETE'
	SIZE_LIST = 'SIZE_LIST'
	SIZE_DETAILS = 'SIZE_DETAILS'


	# PRODUCT_IMAGE PERMISSION
	PRODUCT_IMAGE_CREATE = 'PRODUCT_IMAGE_CREATE'
	PRODUCT_IMAGE_UPDATE = 'PRODUCT_IMAGE_UPDATE'
	PRODUCT_IMAGE_DELETE = 'PRODUCT_IMAGE_DELETE'
	PRODUCT_IMAGE_LIST = 'PRODUCT_IMAGE_LIST'
	PRODUCT_IMAGE_DETAILS = 'PRODUCT_IMAGE_DETAILS'





# ENUM FOR 'ORDER' APP

	# PAYMENT_METHOD PERMISSION
	PAYMENT_METHOD_CREATE = 'PAYMENT_METHOD_CREATE'
	PAYMENT_METHOD_UPDATE = 'PAYMENT_METHOD_UPDATE'
	PAYMENT_METHOD_DELETE = 'PAYMENT_METHOD_DELETE'
	PAYMENT_METHOD_LIST = 'PAYMENT_METHOD_LIST'
	PAYMENT_METHOD_DETAILS = 'PAYMENT_METHOD_DETAILS'

	# ORDER_STATUS PERMISSION
	ORDER_STATUS_CREATE = 'ORDER_STATUS_CREATE'
	ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE'
	ORDER_STATUS_DELETE = 'ORDER_STATUS_DELETE'
	ORDER_STATUS_LIST = 'ORDER_STATUS_LIST'
	ORDER_STATUS_DETAILS = 'ORDER_STATUS_DETAILS'

	# ORDER PERMISSION
	ORDER_CREATE = 'ORDER_CREATE'
	ORDER_UPDATE = 'ORDER_UPDATE'
	ORDER_DELETE = 'ORDER_DELETE'
	ORDER_LIST = 'ORDER_LIST'
	ORDER_DETAILS = 'ORDER_DETAILS'

	# ORDER_ITEM PERMISSION
	ORDER_ITEM_CREATE = 'ORDER_ITEM_CREATE'
	ORDER_ITEM_UPDATE = 'ORDER_ITEM_UPDATE'
	ORDER_ITEM_DELETE = 'ORDER_ITEM_DELETE'
	ORDER_ITEM_LIST = 'ORDER_ITEM_LIST'
	ORDER_ITEM_DETAILS = 'ORDER_ITEM_DETAILS'

	# SHIPPING_ADDRESS PERMISSION
	SHIPPING_ADDRESS_CREATE = 'SHIPPING_ADDRESS_CREATE'
	SHIPPING_ADDRESS_UPDATE = 'SHIPPING_ADDRESS_UPDATE'
	SHIPPING_ADDRESS_DELETE = 'SHIPPING_ADDRESS_DELETE'
	SHIPPING_ADDRESS_LIST = 'SHIPPING_ADDRESS_LIST'
	SHIPPING_ADDRESS_DETAILS = 'SHIPPING_ADDRESS_DETAILS'


 












